version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@1.1.0

_run:
  pull_sonar_image: &pull_sonar_image
    name: Pull Docker sonar-scanner image
    command: |
      echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
      docker pull pagarme/sonar-scanner

jobs:
  test:
    machine: true
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - checkout
      - run:
          name: Build docker-compose containers
          command: docker-compose build
      - run:
          name: Run linter
          command: make lint
      - run:
          name: Run tests
          command: make test-ci
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./
  sonar:
    machine: true
    steps:
      - attach_workspace:
          at: ~/project
      - run: *pull_sonar_image
      - run:
          name: Superbowleto Analysis
          command: make sonar BRANCH=$CIRCLE_BRANCH
  build_image:
    working_directory: ~/superbowleto
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
              mkdir -p images
              export NODE_ENV=production
              docker build --file=Dockerfile.prod -t build:latest .
              docker save -o images/build.tar build:latest
      - persist_to_workspace:
          root: images
          paths:
             -  build.tar
  push_stg:
    working_directory: ~/superbowleto
    machine: true
    steps:
      - attach_workspace:
         at: ~/superbowleto/images
      - run:
          name: Push stg
          command: |
            docker load -i ~/superbowleto/images/build.tar
            export AWS_ACCESS_KEY_ID=$STG_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$STG_AWS_SECRET_ACCESS_KEY
            export AWS_ACCOUNT=$STG_AWS_ACCOUNT
            #ecr-login
            eval $(aws ecr get-login --region us-east-1 --no-include-email)
            # build and push server
            export STG_IMAGE="$STG_AWS_ACCOUNT.dkr.ecr.$REGION.amazonaws.com/superbowleto-stg"
            docker tag build:latest ${STG_IMAGE}:$CIRCLE_TAG
            docker push ${STG_IMAGE}:$CIRCLE_TAG
            docker tag build:latest ${STG_IMAGE}:latest
            docker push ${STG_IMAGE}:latest
  run_stg_migrations:
    working_directory: ~/superbowleto
    machine: true
    steps:
      - checkout
      - run:
          name: run migrations
          command: |
            npm install
            export AWS_ACCESS_KEY_ID=$STG_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$STG_AWS_SECRET_ACCESS_KEY
            export AWS_ACCOUNT=$STG_AWS_ACCOUNT
            export AWS_REGION=$REGION
            node script/run_migrations_task.js
  push_sdx:
    working_directory: ~/superbowleto
    machine: true
    steps:
      - attach_workspace:
         at: ~/superbowleto/images
      - run:
          name: Push sdx
          command: |
            docker load -i ~/superbowleto/images/build.tar
            export AWS_ACCESS_KEY_ID=$SDX_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$SDX_AWS_SECRET_ACCESS_KEY
            export AWS_ACCOUNT=$SDX_AWS_ACCOUNT
            #ecr-login
            eval $(aws ecr get-login --region us-east-1 --no-include-email)
            # build and push server
            export SDX_IMAGE="$SDX_AWS_ACCOUNT.dkr.ecr.$REGION.amazonaws.com/superbowleto-sdx"
            docker tag build:latest ${SDX_IMAGE}:$CIRCLE_TAG
            docker push ${SDX_IMAGE}:$CIRCLE_TAG
            docker tag build:latest ${SDX_IMAGE}:latest
            docker push ${SDX_IMAGE}:latest
  push_prd:
    working_directory: ~/superbowleto
    machine: true
    steps:
      - attach_workspace:
          at: ~/superbowleto/images
      - run:
          name: Push prd
          command: |
            docker load -i ~/superbowleto/images/build.tar
            export AWS_ACCESS_KEY_ID=$PRD_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$PRD_AWS_SECRET_ACCESS_KEY
            export AWS_ACCOUNT=$PRD_AWS_ACCOUNT
            #ecr-login
            eval $(aws ecr get-login --region us-east-1 --no-include-email)
            # build and push server
            export PRD_IMAGE="$PRD_AWS_ACCOUNT.dkr.ecr.$REGION.amazonaws.com/superbowleto-prd"
            docker tag build:latest ${PRD_IMAGE}:$CIRCLE_TAG
            docker push ${PRD_IMAGE}:$CIRCLE_TAG
            docker tag build:latest ${PRD_IMAGE}:latest
            docker push ${PRD_IMAGE}:latest

workflows:
  build_and_deploy:
    jobs:
    - test:
        filters:
          tags:
            only: /^v.*/
    - sonar:
        context: dockerhub
        requires:
          - test
        filters:
          tags:
            only: /^v.*/
    - build_image:
        requires:
          - sonar
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v([0-9]+).([0-9]+).([0-9]+).*$/
    - hold_stg:
        type: approval
        requires:
          - build_image
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v([0-9]+).([0-9]+).([0-9]+).*$/
    - push_stg:
        requires:
          - hold_stg
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v([0-9]+).([0-9]+).([0-9]+).*$/
    # update-task-definition-server-stg
    - aws-ecs/update-task-definition:
        name: update-task-definition-server-stg
        aws-region: $REGION
        aws-access-key-id: $STG_AWS_ACCESS_KEY_ID
        aws-secret-access-key: $STG_AWS_SECRET_ACCESS_KEY
        container-image-name-updates: 'container=superbowleto-s-stg,image-and-tag=${STG_AWS_ACCOUNT_URL}/superbowleto-stg:$CIRCLE_TAG'
        family: 'superbowleto-s-stg'
        requires:
          - push_stg
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v([0-9]+).([0-9]+).([0-9]+).*$/
    - run_stg_migrations:
        requires:
          - update-task-definition-server-stg
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v([0-9]+).([0-9]+).([0-9]+).*$/
    # update-service-server-stg
    - aws-ecs/deploy-service-update:
        name: update-service-server-stg
        aws-region: $REGION
        aws-access-key-id: $STG_AWS_ACCESS_KEY_ID
        aws-secret-access-key: $STG_AWS_SECRET_ACCESS_KEY
        family: 'superbowleto-s-stg'
        cluster-name: 'cluster-stg'
        service-name: 'superbowleto-s-stg'
        requires:
          - run_stg_migrations
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v([0-9]+).([0-9]+).([0-9]+).*$/


    # - hold_sdx:
    #     type: approval
    #     requires:
    #       - build_image
    #     filters:
    #       branches:
    #         ignore: /.*/
    #       tags:
    #         only: /^v([0-9]+).([0-9]+).([0-9]+)$/
    # - hold_prd:
    #     type: approval
    #     requires:
    #       - build_image
    #     filters:
    #       branches:
    #         ignore: /.*/
    #       tags:
    #         only: /^v([0-9]+).([0-9]+).([0-9]+)$/

    # - push_sdx:
    #     requires:
    #       - hold_sdx
    #     filters:
    #       branches:
    #         ignore: /.*/
    #       tags:
    #         only: /^v([0-9]+).([0-9]+).([0-9]+)$/
    # - push_prd:
    #     requires:
    #       - hold_prd
    #     filters:
    #       branches:
    #         ignore: /.*/
    #       tags:
    #         only: /^v([0-9]+).([0-9]+).([0-9]+)$/
    # - deploy_sdx:
    #     requires:
    #       - push_sdx
    #     filters:
    #       branches:
    #         ignore: /.*/
    #       tags:
    #         only: /^v([0-9]+).([0-9]+).([0-9]+)$/
    # - deploy_prd:
    #     requires:
    #       - push_prd
    #     filters:
    #       branches:
    #         ignore: /.*/
    #       tags:
    #         only: /^v([0-9]+).([0-9]+).([0-9]+)$/
